/**
 * Returns portfolio works.
 * In production/build: reads from data/cms-data.json (generated by fetch-cms.mjs).
 * In local dev without CMS data: falls back to data/works.js (hardcoded).
 */

import { existsSync } from 'fs'
import { join } from 'path'
import { createRequire } from 'module'

export function getWorks() {
  const cmsPath = join(process.cwd(), 'data/cms-data.json')

  if (existsSync(cmsPath)) {
    const require = createRequire(import.meta.url)
    return require(cmsPath)
  }

  // Fallback to hardcoded data
  const { works } = require('../data/works.js')
  return works
}

export const categories = [
  'All',
  'Strategy & Brand',
  'Film & Production',
  'Campaigns & Partnerships',
  'Branded Content',
]
